# src/sdz/BlogBundle/Resources/config/routing.yml

site_home:
    pattern:   /home
    defaults:  { _controller: siteSiteBundle:Site:index }

site_service:
    pattern:   /service
    defaults:  { _controller: siteSiteBundle:Site:service }

site_agence:
    pattern:   /agence
    defaults:  { _controller: siteSiteBundle:Site:agence }

site_devis:
    pattern:   /devis
    defaults:  { _controller: siteSiteBundle:Site:devis }
    requirements:
        _method:  POST|GET

site_colis_interdit:
    pattern:   /colis_interdit
    defaults:  { _controller: siteSiteBundle:Site:colis_interdit }

site_conditions_generales:
    pattern:   /conditions_generales
    defaults:  { _controller: siteSiteBundle:Site:conditions_generales }

site_mentions_legales:
    pattern:   /mentions_legales
    defaults:  { _controller: siteSiteBundle:Site:mentions_legales }

site_contact:
    pattern:   /contact
    defaults:  { _controller: siteSiteBundle:Site:contact }
    requirements:
        _method:  POST|GET

