# src/sdz/BlogBundle/Resources/config/routing.yml

site_index:
    pattern:   /
    defaults:  { _controller: siteSiteBundle:Site:index }

site_home:
    pattern:   /home
    defaults:  { _controller: siteSiteBundle:Site:index }

site_service:
    pattern:   /service
    defaults:  { _controller: siteSiteBundle:Site:service }

site_agences:
    pattern:   /agences
    defaults:  { _controller: siteSiteBundle:Site:agences }

site_devis:
    pattern:   /devis
    defaults:  { _controller: siteSiteBundle:Site:devis }
    requirements:
        _method:  POST|GET

site_colis_interdits:
    pattern:   /colis_interdits
    defaults:  { _controller: siteSiteBundle:Site:colis_interdits }

site_conditions_generales:
    pattern:   /conditions_generales
    defaults:  { _controller: siteSiteBundle:Site:conditions_generales }

site_mentions_legales:
    pattern:   /mentions_legales
    defaults:  { _controller: siteSiteBundle:Site:mentions_legales }

site_contact:
    pattern:   /contact
    defaults:  { _controller: siteSiteBundle:Site:contact }
    requirements:
        _method:  POST|GET

